### ISSUE TITLE
A little CMake code review

### ISSUE THREAD

**Issue by alexreinking** [buddly27/pytest-cmake#1]
I use PyTest with a CMake project and have been meaning to do something like this for a while, so thanks for putting in the legwork and MIT-licensing it!

I don't use third-party CMake code without reading it and while this is generally very well-written, I wanted to offer a few ideas for improvement:

### Minimum version

You need to pick and check a minimum version. This is not a good approach:

https://github.com/buddly27/pytest-cmake/blob/fdaab76631dbc7f757a1db5d33a241bfeb48bf72/cmake/PytestAddTests.cmake#L2

It essentially makes all your code UB since _anything_ could change in a future version of CMake. I suggest determining a minimum version (say 3.20, see below*) by testing it with every version until it breaks and then using:

```
cmake_minimum_required(VERSION 3.20...3.25)
```

This way you'll get the same "newest policy" behavior for all versions that currently exist, but you won't have to worry about things breaking for your users when they upgrade CMake.

This should also be at the top of FindPytest.cmake, not just PytestAddTests.cmake

Whichever CMake minimum version you land on, you should test using both that version and the latest CMake version on GHA. This will help you avoid accidentally breaking the minimum version.

#### *Hard minimum, based on implementation

The call to `cmake_path` here forces the minimum version to be at least 3.20.

https://github.com/buddly27/pytest-cmake/blob/fdaab76631dbc7f757a1db5d33a241bfeb48bf72/cmake/FindPytest.cmake#LL75C9-L75C19

The use of `TEST_INCLUDE_FILES` here forces the minimum version to be at least 3.10.

https://github.com/buddly27/pytest-cmake/blob/fdaab76631dbc7f757a1db5d33a241bfeb48bf72/cmake/FindPytest.cmake#L126-L127

### Cache usage

The `mark_as_advanced` function only makes sense for cache variables. The variables `_version` and `PYTEST_VERSION` are _not_ cache variables! See here:

https://github.com/buddly27/pytest-cmake/blob/fdaab76631dbc7f757a1db5d33a241bfeb48bf72/cmake/FindPytest.cmake#L36

https://github.com/buddly27/pytest-cmake/blob/fdaab76631dbc7f757a1db5d33a241bfeb48bf72/cmake/FindPytest.cmake#L39

On CMake 3.17+, this is a no-op, which is merely annoying, but on earlier versions it creates a blank cache entry, which is actually bad and pollutes the GUI.

### Find module subtleties

In your call to `find_package_handle_standard_args`, you should pass `HANDLE_COMPONENTS` to correctly reject `find_package` calls that specify components that don't exist. You should also check `CMAKE_VERSION` and pass `HANDLE_VERSION_RANGE` on CMake 3.19+.

https://github.com/buddly27/pytest-cmake/blob/fdaab76631dbc7f757a1db5d33a241bfeb48bf72/cmake/FindPytest.cmake#L41-L47

### Imported targets

You should not make imported targets global by default because it cannot be un-done. Let your users set `IMPORTED_GLOBAL` if they want.

https://github.com/buddly27/pytest-cmake/blob/fdaab76631dbc7f757a1db5d33a241bfeb48bf72/cmake/FindPytest.cmake#L50

Your function won't work globally anyway since it refers to the variable `_PYTEST_DISCOVER_TESTS_SCRIPT`. You can fix this on CMake 3.17+ by using [`CMAKE_CURRENT_FUNCTION_LIST_DIR`](https://cmake.org/cmake/help/latest/variable/CMAKE_CURRENT_FUNCTION_LIST_DIR.html) inside the function and deleting the private variable.

### Environment modification

If you decide to take CMake 3.22 as a minimum, you can significantly simplify parts of your implementation using the `ENVIRONMENT_MODIFICATION` test property. 

https://cmake.org/cmake/help/latest/prop_test/ENVIRONMENT_MODIFICATION.html

### Quoting

You probably want quotes around `${TEST_GROUP_NAME}` in here since as of CMake 3.19+, arbitrary characters are allowed in test names. See also [CMP0110](https://cmake.org/cmake/help/latest/policy/CMP0110.html)

https://github.com/buddly27/pytest-cmake/blob/fdaab76631dbc7f757a1db5d33a241bfeb48bf72/cmake/PytestAddTests.cmake#L14-L28

**Comment by buddly27** [comment]
This is the best code review I have got in a very long time, thank you so much for taking the time to contribute, I agree with all your points and learnt a lot in the process :)

> *Hard minimum, based on implementation

I actually indicated 3.20+ as a minimum version on the badge within the README page, but setting the version range as you did is way cleaner. I will also update the Github workflow to properly test minimum and maximum versions as you suggested.

> Environment modification

Unfortunately I need to keep compatibility with 3.20 at the moment, but I didn't know about this test property and this will be a great argument to upgrade!

**Comment by alexreinking** [comment]
> I actually indicated 3.20+ as a minimum version on the badge within the README page

Ah, I should have read it more carefully. Having read your Reddit post, I just sort of skimmed it. Glad we landed on the same minimum.

> Unfortunately I need to keep compatibility with 3.20 at the moment, but I didn't know about this test property and this will be a great argument to upgrade!

Yep! Something to think about in the future.

> This is the best code review I have got in a very long time, thank you so much for taking the time to contribute, I agree with all your points and learnt a lot in the process :)

You're welcome, and I'm happy to help! :slightly_smiling_face:
